
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HostelServiceImplService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/hostelserver/hostelWS?wsdl")
public class HostelServiceImplService
    extends Service
{

    private final static URL HOSTELSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOSTELSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HOSTELSERVICEIMPLSERVICE_QNAME = new QName("http://service/", "HostelServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hostelserver/hostelWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOSTELSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HOSTELSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HostelServiceImplService() {
        super(__getWsdlLocation(), HOSTELSERVICEIMPLSERVICE_QNAME);
    }

    public HostelServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOSTELSERVICEIMPLSERVICE_QNAME, features);
    }

    public HostelServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HOSTELSERVICEIMPLSERVICE_QNAME);
    }

    public HostelServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOSTELSERVICEIMPLSERVICE_QNAME, features);
    }

    public HostelServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HostelServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HostelService
     */
    @WebEndpoint(name = "HostelServiceImplPort")
    public HostelService getHostelServiceImplPort() {
        return super.getPort(new QName("http://service/", "HostelServiceImplPort"), HostelService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HostelService
     */
    @WebEndpoint(name = "HostelServiceImplPort")
    public HostelService getHostelServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "HostelServiceImplPort"), HostelService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOSTELSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HOSTELSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HOSTELSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
